### PR TITLE
conversion to typescript with unit tests

### PR DESCRIPTION
**Pull request by j-d-carmichael**
- convert to typescrpt
- built with webpack and minified
- tested css to json
- tested json to css
- added linter
- updated the scripts

### CODE REVIEW

**Comment by johndcarmichael** [comment]
Using this myself installed from github and it now seems stable.

**Comment by aramk** [comment]
Thanks a lot for modernising this library!

**Comment by j-d-carmichael** [comment]
welcome! looking forward to seeing this on npm

**Comment by j-d-carmichael** [comment]
@aramk   is this the correct npm url:  https://www.npmjs.com/package/cssjson  ?

**Comment by j-d-carmichael** [comment]
@aramk  when can we see this on npm?

**Pull request merged**
